### ISSUE TITLE
 Unsupported packages - inconsolata and arydshln

### ISSUE THREAD

**Issue by mark-friedman** [arXiv/html_feedback#1563]
### Description

I saw the following error: 
>HTML conversions sometimes display errors due to content that did not convert correctly from the source. This paper uses the following packages that are not yet supported by the HTML conversion tool. Feedback on these issues are not necessary

### (Required) What is this issue most closely related to? Select one.

Other

### Internal issue ID

c27fd617-89cd-4e1c-98d9-866c2f652bfc

### Paper URL

https://arxiv.org/html/2406.06469v1

### Browser

Chrome/125.0.0.0

### Device Type

Desktop

**Comment by dginev** [comment]
Thank you for your report - the specific issue is now solved.

We have regenerated the article and you should be able to see an improvement.

Feel free to open new tickets for any remaining issues.

**Comment by mark-friedman** [comment]
I still see the following, which implies that `arydshln.sty` is still not supported:

> HTML conversions [sometimes display errors](https://info.dev.arxiv.org/about/accessibility_html_error_messages.html) due to content that did not convert correctly from the source. This paper uses the following packages that are not yet supported by the HTML conversion tool. Feedback on these issues are not necessary; they are known and are being worked on.
>
>failed: arydshln.sty
>Authors: achieve the best HTML results from your LaTeX submissions by following these [best practices](https://info.arxiv.org/help/submit_latex_best_practices.html).
