### ISSUE TITLE
Improve article : 2208.05923v3

### ISSUE THREAD

**Issue by JessRiedel** [arXiv/html_feedback#39]
## Describe the issue

**Description**: The over bar is not displaying well.  See for instance the bar over the \ell character in the first inline equation in Appendix C of this paper (2208.05923v3). The PDF is very clear here, but the HTML is bad.

HTML: 

<img width="76" alt="Screenshot 2023-08-23 at 6 43 56 PM" src="https://github.com/arXiv/html_feedback/assets/16365564/bc6481e7-8da6-4ab8-a257-6db09a51565f">

PDF:

<img width="102" alt="Screenshot 2023-08-23 at 6 44 09 PM" src="https://github.com/arXiv/html_feedback/assets/16365564/5c3fd293-c104-4cc9-a662-07bff27c93c5">

## Auto Fill Data - !!! Please do not edit below this line !!!
----------------------------------------------------------------------------------------

Id: 8600aa4f-b789-4efb-82d0-853c6eb50020

**Comment by dginev** [comment]
Thank you for your report - the specific issue is now solved.

We have regenerated the article and you should be able to see an improvement.

I suspect further refinements will be available as MathML Core improves in browsers, but the core problem you had reported was due to not loading a math font, which is now corrected.

**Comment by JessRiedel** [comment]
I'm not sure if maybe the HTML didn't propagate, but fwiw, the issue persist for me (on both mobile and desktop). I reloaded the page to be sure. 

Desktop: 

<img width="143" height="37" alt="Image" src="https://github.com/user-attachments/assets/d4b19665-bcb6-494c-a349-6a4f98b20db1" />

Mobile:

![Image](https://github.com/user-attachments/assets/4d2621a3-befa-4360-8ee0-7425888ba801)

**Comment by JessRiedel** [comment]
(I guess one could say this is _better_, but the bar is still touching the ell, and it's off center; maybe that's what you mean by "further refinement", in which case just ignore me.)

**Comment by dginev** [comment]
Thank you for double-checking.

I think that is the best MathML Core can do today. We're tracking this over there at:
https://github.com/w3c/mathml-core/issues/254

The hope is that one day a browser update will resolve the remaining inaccuracy.
