### ISSUE TITLE
mobile view, green box page fit and text alignment

### ISSUE THREAD

**Issue by willhansen** [arXiv/html_feedback#5287]
### Description

At "Definition 1: Feature" on mobile firefox

### (Optional:) Please add any files, screenshots, or other information here.

![Image](https://github.com/user-attachments/assets/6c15e5c7-9d9d-451e-a88a-ab72afa03139)

### (Required) What is this issue most closely related to? Select one.

Other

### Internal issue ID

76f37825-f6d4-4e67-ae13-98216ac41acc

### Paper URL

https://arxiv.org/html/2404.14082v3

### Browser

Firefox/145.0

### Device Type

Android

**Comment by dginev** [comment]
Thank you for your report - the specific issue is now solved.

We have regenerated the article and you should be able to see an improvement.

**Comment by willhansen** [comment]
Still appears cut off on the right side (at least in the firefox mobile viewer)

<img width="950" height="873" alt="Image" src="https://github.com/user-attachments/assets/b2478cf0-8c18-4d70-b57a-94081d2a0c57" />

Also, the box appears unusually small in the ~~regular~~ desktop view:
HTML:

<img width="970" height="388" alt="Image" src="https://github.com/user-attachments/assets/30ef49bd-4809-49c6-886b-d8e0d0ff23ec" />

PDF:

<img width="970" height="388" alt="Image" src="https://github.com/user-attachments/assets/8a4469b7-cecb-4812-8def-6eca2e562f31" />

**Comment by dginev** [comment]
I am not sure how precisely these can match up with the current SVG target for `{tcolorbox}`. In particular, latexml sets concrete width and height sizes that don't reflow on mobile. But maybe some additional allowances can be made.

I will keep the issue also as a marker for us to consider a native HTML+CSS implementation which will be able to reflow well on mobile.

Thanks for reviewing.
